#!/bin/sh

modprobe lis331dlh-i2c

echo "loading qt demo..."
export QT_QPA_PLATFORM=eglfs
export QT_QPA_EGLFS_ALWAYS_SET_MODE=1
cd /home/root/Seeed_Python_ReTerminalQt5Examples/src/
python3 main.py &
echo "qt demo start ok!"

